apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-performance-us-central1
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:15

  # One primary and two replicas (one at least synchronous)
  instances: 3
  minSyncReplicas: 1
  maxSyncReplicas: 1

  # Require different zones and different nodes with label "workload=postgres"
  # topologySpreadConstraints:
  # - maxSkew: 1
  #  topologyKey: topology.kubernetes.io/zone
  #  whenUnsatisfiable: DoNotSchedule
  #  labelSelector:
  #    matchLabels:
  #      cnpg.io/cluster: postgres-performance-us-central1
  # affinity:
  #  tolerations:
  #  - key: "workload"
  #    operator: "Equal"
  #    value: "postgres"
  #    effect: "NoExecute"
#   topologySpreadConstraints:
#    - maxSkew: 1
#      topologyKey: kubernetes.io/hostname
#      whenUnsatisfiable: DoNotSchedule

  # Request Guaranteed QoS
  resources:
    requests:
      memory: '12Gi'
      cpu: 1.5
    limits:
      memory: '12Gi'
      cpu: 1.5

  startDelay: 300
  stopDelay: 300
  switchoverDelay: 600

  # Volume with PGDATA
  storage:
    storageClass: standard-rwo
    size: 80Gi

  # Volume for WALs
  walStorage:
    storageClass: standard-rwo
    size: 10Gi

  # Cluster initialization
  bootstrap:
    initdb:
      dataChecksums: true
      walSegmentSize: 64
      postInitSQL:
        - CREATE DATABASE pgbench OWNER app

  # PostgreSQL configuration
  postgresql:
    parameters:
      # Connections
      max_connections: '100'

      # Memory configuration
      shared_buffers: '4GB'
      maintenance_work_mem: '1GB'
      effective_cache_size: '15GB'
      shared_memory_type: 'sysv'
      dynamic_shared_memory_type: 'sysv'

      # Checkpoint management
      min_wal_size: '1GB'
      max_wal_size: '5GB'
      checkpoint_timeout: '900s'
      checkpoint_completion_target: '0.9'

      # Log configuration
      log_checkpoints: 'on'
      log_lock_waits: 'on'
      log_min_duration_statement: '1000'
      log_statement: 'ddl'
      log_temp_files: '1024'
      log_autovacuum_min_duration: '1s'

      # Enable pg_stat_statements
      pg_stat_statements.max: '10000'
      pg_stat_statements.track: 'all'

      # Replication
      hot_standby_feedback: 'on'
      max_slot_wal_keep_size: '8GB'

  monitoring:
    enablePodMonitor: true

  backup:
    volumeSnapshot:
      className: cnpg-snapshotclass
    barmanObjectStore:
      destinationPath: gs://postgres-performance-us-central1/
      googleCredentials:
        gkeEnvironment: true
      data:
        compression: gzip
        jobs: 2
        immediateCheckpoint: true
      wal:
        compression: gzip
        maxParallel: 2
    retentionPolicy: '7d'

  serviceAccountTemplate:
    metadata:
      annotations:
        iam.gke.io/gcp-service-account: postgres-performance-user@songsunny-joonix.iam.gserviceaccount.com

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres-performance-us-central1-backup
spec:
  schedule: '0 0 0 * * *'
  backupOwnerReference: self
  method: volumeSnapshot
  cluster:
    name: postgres-performance-us-central1
  immediate: true
